on:
  release:
    types:
      - created

name: Release

jobs:

  sdist:
    name: Creating source release & pure wheel

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Installing
      run: poetry install --no-interaction

    - name: Building documentation
      run: |
        cd docs && make clean && make html

    - name: Publishing documentation
      run: |
        ghp-import -f -n docs/_build/html

    - name: Publishing
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry config pypi-token.pypi $PYPI_TOKEN
        poetry publish --build
