on:
  release:
    types:
      - created

name: Release

jobs:

  sdist:
    name: Creating source release & pure wheel

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Publishing
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry config pypi-token.pypi $PYPI_TOKEN
        poetry publish --build
